#!/bin/sh -e
#
# This file is part of xmangahere project.
#
# Copyright (C) 2019 aliceinthedark <don't @ me>
# All Rights Reserved
# 
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# LICENSE.md for more details.
#

query="$*"
[ "$query" ] || query=$(rofi -dmenu -lines 0)

if [ -z "$query" ]; then
    echo "Nothing to search here..."
    exit 1
fi

echo "Searching for $query..."

title=$(./search.py "$query" | rofi -dmenu)

if [ -z "$title" ]; then
    echo "Nothing to search here..."
    exit 1
fi

echo "Loading volumes for $title..."

volume=$(./loadvolumes.py $title | rofi -dmenu)

echo "Loading page links for $volume..."

page_links=$(./loadpages.py "$volume" | tr '\n' ' ')

echo "Page links are loaded. Saving images..."

pages=$(./saveimages.py "$page_links")

echo "Oppening a viewer..."

feh -. $pages
