#!/usr/bin/sh

SEARCH=$(rofi -dmenu -lines 0)

if [ -z "$SEARCH" ]; then
    echo "Nothing to search here..."
    exit 1
fi

echo "Searching for $SEARCH..."

RESULTS=$(./search.py "$SEARCH")

TITLE=$(echo $RESULTS | tr ' ' '\n' | rofi -dmenu)

if [ -z "$TITLE" ]; then
    echo "Nothing to search here..."
    exit 1
fi

echo "Loading volumes for $TITLE..."

VOLUMES=$(./loadvolumes.py $TITLE)

VOLUME=$(echo $VOLUMES | tr ' ' '\n' | rofi -dmenu)

echo "Loading page links for $VOLUME..."

PAGES=$(./loadpages.py "$VOLUME")

echo "Page links are loaded. Oppening a viewer..."

feh $PAGES
